backend:
  name: github
  repo: GhostRicity/headlesWall
  branch: master
  use_graphql: true


# Uncomment local_backend when you need to develop in your local
#local_backend: true # run npx netlify-cms-proxy-server for local testing

media_folder: "static/assets"
public_folder: "/assets"


collections:
  - label: Hero
    name: hero
    folder: scr/content/hero/hero.md
    create: true
    fields:
      - { name: title, label: Title, widget: 'string' }
      - { name: description, label: Description, widget: string }
      - { name: 'featuredImage', label: 'Featured Image', widget: 'image', required: true,  tagname: '' }
       - label: "CTA"
          name: "cta"
          widget: "object"
          fields:
            - name: "ctaText"
              label: "CTA text"
              widget: "string"
            - name: "ctaLink"
              label: "CTA Link"
              widget: "string"
